[build]
  Command = "npm run build && npm run build:lambda"
  Functions = "lambda"
  Publish = "build"
[context.production]
  Command = "npm run build && npm run build:lambda"
[context.deploy-preview]
  Command = "npm run build && npm run build:lambda"
